version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Install tools
          command: |
            wget -qO- https://download.docker.com/linux/static/stable/x86_64/docker-17.03.2-ce.tgz | tar -zxf- -C /bin
      - run:
          name: Build Binary
          command: |
            docker build -t demo-builder -f Dockerfile.build .
            docker run --rm demo-builder > demo
      - run:
          name: Build Image
          command: docker build -t demo .
      - run:
          name: Install kubectl
          command: gcloud components install kubectl
