version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Image
          command: docker build -t demo .
