version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Install tools
          command: |
            apk add -U openssl docker
            cd /bin
            wget -qO- https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl > kubectl
            chmod +x kubectl
      - run:
          name: Build Binary
          command: |
            docker build -t demo-builder -f Dockerfile.build .
            docker run --rm demo-builder > demo
      - run:
          name: Build Image
          command: docker build -t demo .
      - run:
          name: Install kubectl
          command: gcloud components install kubectl
